# docker compose build backend && docker compose up --build -d && docker compose logs -f backend

name: db-embedding
services:
  db:
#    image: postgres:${DB_VERSION:-18}
    image: pgvector/pgvector:pg${DB_VERSION:-18}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/${DB_VERSION:-18}/docker
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


  backend:
    build:
      context: .

    volumes:
      - ./src:/app/src
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env


  celery-worker:
    build:
      context: .
    env_file:
      - .env
    entrypoint: ./run_celery_worker.sh
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  staticfiles: