# docker compose build backend && docker compose up --build -d && docker compose logs -f backend

name: db-embedding
services:
  db:
#    image: postgres:${DB_VERSION:-18}
#    image: pgvector/pgvector:pg${DB_VERSION:-18}
    build:
      context: ./dockers
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - DB_VERSION=${DB_VERSION:-18}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/${DB_VERSION:-18}/docker
    volumes:
#      - ./dockers/ukrainian_fts.sql:/docker-entrypoint-initdb.d/ukrainian_fts.sql:ro
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data


  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRA=${EXTRA:-none}

    volumes:
      - ./src:/app/src
      - staticfiles:/app/staticfiles
      - ./data/models:/app/data/models
#      - models:/app/data/models
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SERVE_STATIC_FILES=True
    env_file:
      - .env


  celery-worker:
    build:
      context: .
    env_file:
      - .env
    entrypoint: ./run_celery_worker.sh
    volumes:
      - ./src:/app/src
      - ./data/models:/app/data/models
#      - models:/app/data/models
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  staticfiles:
  redis_data:
  models: