[project]
name = "django-db-embedding"
version = "0.0.1"
description = "A Django app to integrate Database vector embeddings for semantic search."
requires-python = ">=3.12"
dependencies = [
    "psycopg[binary,pool]>=3.2.12",
    "pgvector>=0.4.1",
    "python-dotenv>=1.2.1",
    "django>=5.2.7",
    "orjson>=3.11.4",
    "django-ninja>=1.4.5",
    "redis[hiredis]>=7.0.1",
    "celery>=5.5.3",
    "celery-types>=0.23.0",
    "openai>=2.6.1",
    "cohere>=5.20.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.2",
]
deploy = [
    "gunicorn>=23.0.0",
    "uvicorn>=0.38.0",
    "whitenoise[brotli]>=6.11.0",
]
ml = [
  "sentence-transformers>=5.1.2",
  "torch>=2.9.0",
]


[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120


[tool.uv]
index-url = "https://pypi.org/simple"
required-environments = [
    "sys_platform == 'win32'",
    "sys_platform == 'linux'",
    "sys_platform == 'darwin'",
]


[[tool.uv.index]]
url = "https://pypi.org/simple/"
default = true

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"


