# Generated by Django 5.2.7 on 2025-11-03 01:50

import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("items", "0001_initial"),
        ("items", "0002_alter_item_search_vector"),
        ("items", "0003_item_updated_at_itemembedding_updated_at_and_more"),
        ("items", "0004_alter_queryembedding_vector"),
        ("items", "0005_alter_itemembedding_model"),
        ("items", "0006_alter_itemembedding_model"),
        ("items", "0007_alter_itemembedding_model"),
        ("items", "0008_alter_itemembedding_model"),
        ("items", "0009_alter_itemembedding_vector_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vector", pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ("model", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="embedding", to="items.item"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query_hash", models.CharField(max_length=64, unique=True)),
                ("vector", pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
