# Generated by Django 5.2.7 on 2025-10-31 00:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_updated_at_itemembedding_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryembedding",
            name="vector",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
