# Generated by Django 5.2.7 on 2025-10-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_queryembedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemembedding',
            name='model',
            field=models.CharField(default='text-embedding-3-large', max_length=50),
        ),
    ]
