# Generated by Django 5.2.7 on 2025-10-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_itemembedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemembedding',
            name='model',
            field=models.CharField(default='text-embedding-3-small', max_length=50),
        ),
    ]
