# Generated by Django 5.2.7 on 2025-11-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_alter_itemembedding_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemembedding",
            name="model",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
