# Generated by Django 5.2.7 on 2025-11-24 07:41

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_alter_itemembedding_vector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemembedding",
            name="vector",
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queryembedding",
            name="vector",
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
