"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from os import environ
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = environ.get("SECRET_KEY", "super-secret-key")
DEBUG = environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = environ.get("ALLOWED_HOSTS", "*").split(",")
SERVE_STATIC_FILES = environ.get("SERVE_STATIC_FILES", "False").lower() == "true"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "items",
    "embeddings",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if SERVE_STATIC_FILES:
    MIDDLEWARE.insert(0, "whitenoise.middleware.WhiteNoiseMiddleware")


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": environ.get("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": environ.get("DB_NAME", "postgres"),
        "USER": environ.get("DB_USER", "postgres"),
        "PASSWORD": environ.get("DB_PASSWORD", ""),
        "HOST": environ.get("DB_HOST", "db"),
        "PORT": environ.get("DB_PORT", "5432"),
        "OPTIONS": {
            "pool": environ.get("DB_POOL", "True").lower() == "true",
            # "options": "-c statement_timeout=5000",
            # "connect_timeout": 5,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/Kyiv"
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("ua", _("Ukrainian")),
    ("en", _("English")),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

REDIS_URL = environ.get("REDIS_URL")

if REDIS_URL:
    try:
        import redis

        redis_connection = redis.from_url(REDIS_URL)
        redis_connection.ping()
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": REDIS_URL,
            }
        }
        SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
    except Exception:
        print("Redis connection error")

USE_HNSW_INDEX = True
CELERY_BROKER_URL = environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
FULLTEXT_SEARCH_ENABLED = environ.get("FULLTEXT_SEARCH_ENABLED", "True").lower() == "true"
FULLTEXT_SEARCH_LANGUAGES = environ.get("FULLTEXT_SEARCH_LANGUAGES", "english,ukrainian").split(",")
VECTOR_EMBEDDIG_ENABLED = environ.get("VECTOR_EMBEDDIG_ENABLED", "True").lower() == "true"
VECTOR_EMBEDDIG_DIMENSIONS = int(environ.get("VECTOR_EMBEDDIG_DIMENSIONS", 1536))
OPENAI_API_KEY = environ.get("OPENAI_API_KEY")
OPENAI_API_BASE = environ.get("OPENAI_API_BASE")
EMBEDDIG_MODEL_NAME = environ.get("EMBEDDIG_MODEL_NAME", "text-embedding-3-small")
API_DELAY_TIME_ENABLED = (environ.get("API_DELAY_TIME_ENABLED", "True").lower() == "true",)
API_DELAY_TIME_RPM = int(environ.get("API_DELAY_TIME_RPM", 95))  # RPM


# Logging settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": environ.get("DJANGO_LOG_LEVEL", default="DEBUG" if DEBUG else "INFO"),
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "console_debug": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": environ.get("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": environ.get("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": environ.get("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
        "django.template": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
LOGGING_APPS = set(("items", "embeddings"))
for app in LOGGING_APPS:
    LOGGING["loggers"][app] = {
        "handlers": ["console_debug"],
        "level": "DEBUG" if DEBUG else "WARNING",
        "propagate": False,
    }
